apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: observability
spec:
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
---
kind: Endpoints
apiVersion: v1
metadata:
  name: elasticsearch-logging
  namespace: observability
subsets:
  - addresses:
      - ip: 10.60.101.12
      - ip: 10.60.101.3
      - ip: 10.60.101.5
    ports:
      - port: 9200
