kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus
  namespace: cicd
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
