apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cicd
  labels:
    app: postgres
spec:
  type: NodePort        #指定为 NodePort 方式暴露出口
  ports:
    - name: server
      port: 5432
      targetPort: 5432
      nodePort: 30543   #指定 Nodeport 端口
      protocol: TCP
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: cicd
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.3-alpine
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB             #PostgreSQL 数据库名称
          value: "sonarDB"
        - name: POSTGRES_USER           #PostgreSQL 用户名
          value: "sonarUser"
        - name: POSTGRES_PASSWORD       #PostgreSQL 密码
          value: "123456"
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 2000m
            memory: 2048Mi
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres         #引用上面创建的 PVC
