apiVersion: v1
kind: LimitRange
metadata:
  name: container-resources
  namespace: default
spec:
  limits:
    - type: Pod  # 对Pod中所有容器资源总和进行限制
      max:
        cpu: 4000m
        memory: 2048Mi 
      min:
        cpu: 50m
        memory: 32Mi 
      maxLimitRequestRatio:
        cpu: 5
        memory: 5
    - type: Container  # 对Pod中所有容器资源进行限制
      max:
        cpu: 2000m
        memory: 1024Mi
      min:
        cpu: 50m
        memory: 32Mi 
      maxLimitRequestRatio:
        cpu: 5
        memory: 5
      default:
        cpu: 100m
        memory: 64Mi
      defaultRequest:
        cpu: 50m
        memory: 32Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: storage-resources
  namespace: default
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 10Gi
    min:
      storage: 1Gi
