apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: default
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 5Gi
    limits.cpu: "20"
    limits.memory: 10Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-resources
  namespace: default
spec:
  hard:
    requests.storage: "100Gi"
    persistentvolumeclaims: "10"
    rbd.storageclass.storage.k8s.io/requests.storage: "100Gi"
    rbd.storageclass.storage.k8s.io/persistentvolumeclaims: "10"
    cephfs.storageclass.storage.k8s.io/requests.storage: "100Gi"
    cephfs.storageclass.storage.k8s.io/persistentvolumeclaims: "10"
    requests.ephemeral-storage: "10Gi"
    limits.ephemeral-storage: "10Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: default
spec:
  hard:
    pods: "10"
    replicationcontrollers: "10"
    services: "10"
    services.loadbalancers: "0"
    services.nodeports: "5"
    configmaps: "10"
    secrets: "10"
    resourcequotas: "10"
