global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_from: '407789703@qq.com'
  smtp_auth_username: '407789703@qq.com'
  smtp_auth_password: 'zeyfhxccabg'
  smtp_require_tls: false
  smtp_hello: 'cloud'
 
templates:
- '*.tmpl'
 
route:
  group_by: ['alertname','job']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 8h
  receiver: 'email'
  routes:
  - receiver: "null"
    match:
      alertname: 'CPUThrottlingHigh'
 
receivers:
- name: 'null'
- name: 'email'
  email_configs:
  - to: '407789703@qq.com'
    require_tls: false
    headers:
      Subject: '{{ template "email.default.subject" . }}'
    html: '{{ template "email.default.html" . }}'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal:
  - alertname
  - instance
